export const APP_LOADING = 'APP_LOADING';
export const APP_LOADING_FULFILLED = 'APP_LOADING_FULFILLED';

export const GLOBAL_ERROR = 'GLOBAL_ERROR';

export const AUTH_CHECK = 'AUTH_CHECK';

export const COURSE = 'COURSE';
export const COURSE_SEARCH = 'COURSE_SEARCH';

export const PROFESSOR = 'PROFESSOR';
export const PROFESSOR_SEARCH = 'PROFESSOR_SEARCH';

export const USER_REGISTER = 'USER_REGISTER';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_PREREG = 'USER_LOGIN_PREREG';
export const USER_LOGIN_REJECTED = 'USER_LOGIN_REJECTED';
export const USER_LOGIN_FULFILLED = 'USER_LOGIN_FULFILLED';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_FULFILLED = 'USER_LOGOUT_FULFILLED';
