export const APP_LOADING = 'APP_LOADING';
export const APP_LOADING_FULFILLED = 'APP_LOADING_FULFILLED';

export const GLOBAL_ERROR = 'GLOBAL_ERROR';

export const AUTH_CHECK = 'AUTH_CHECK';

export const TEST = 'TEST';
export const TEST_REJECTED = 'TEST_REJECTED';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_PREREG = 'USER_LOGIN_PREREG';
export const USER_LOGIN_REJECTED = 'USER_LOGIN_REJECTED';
export const USER_LOGIN_FULFILLED = 'USER_LOGIN_FULFILLED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_FULFILLED = 'USER_LOGOUT_FULFILLED';
